Repository KTB-6-Joing/joing-server, pull requests merged in 2024-11, with the labels that each got.

#6 JOING-18 feat: 카카오 소셜 로그인 및 회원가입 API 개발
  build.gradle
  src/main/java/com/ktb/joing/common/config/RedisConfig.java
  src/main/java/com/ktb/joing/common/config/SecurityConfig.java
  src/main/java/com/ktb/joing/domain/auth/cookie/CookieUtils.java
  src/main/java/com/ktb/joing/domain/auth/dto/CustomOAuth2User.java
  src/main/java/com/ktb/joing/domain/auth/dto/KakaoResponse.java
  src/main/java/com/ktb/joing/domain/auth/dto/OAuth2Response.java
  src/main/java/com/ktb/joing/domain/auth/dto/UserDto.java
  src/main/java/com/ktb/joing/domain/auth/exception/AuthErrorCode.java
  src/main/java/com/ktb/joing/domain/auth/exception/AuthException.java
  src/main/java/com/ktb/joing/domain/auth/handler/CustomSuccessHandler.java
  src/main/java/com/ktb/joing/domain/auth/jwt/JwtFilter.java
  src/main/java/com/ktb/joing/domain/auth/jwt/JwtUtil.java
  src/main/java/com/ktb/joing/domain/auth/jwt/RefreshToken.java
  src/main/java/com/ktb/joing/domain/auth/jwt/RefreshTokenRepository.java
  src/main/java/com/ktb/joing/domain/auth/jwt/TokenService.java
  src/main/java/com/ktb/joing/domain/auth/redis/TempUser.java
  src/main/java/com/ktb/joing/domain/auth/redis/TempUserRepository.java
  src/main/java/com/ktb/joing/domain/auth/service/CustomOAuth2UserService.java
  src/main/java/com/ktb/joing/domain/user/controller/UserController.java
  src/main/java/com/ktb/joing/domain/user/dto/request/CreatorSignupRequest.java
  src/main/java/com/ktb/joing/domain/user/dto/request/ProductManagerSignupRequest.java
  src/main/java/com/ktb/joing/domain/user/entity/Category.java
  src/main/java/com/ktb/joing/domain/user/entity/Creator.java
  src/main/java/com/ktb/joing/domain/user/entity/FavoriteCategory.java
  src/main/java/com/ktb/joing/domain/user/entity/MediaType.java
  src/main/java/com/ktb/joing/domain/user/entity/ProductManager.java
  src/main/java/com/ktb/joing/domain/user/entity/Role.java
  src/main/java/com/ktb/joing/domain/user/entity/SocialProvider.java
  src/main/java/com/ktb/joing/domain/user/entity/User.java
  src/main/java/com/ktb/joing/domain/user/exception/UserErrorCode.java
  src/main/java/com/ktb/joing/domain/user/exception/UserException.java
  src/main/java/com/ktb/joing/domain/user/repository/UserRepository.java
  src/main/java/com/ktb/joing/domain/user/service/UserService.java
  src/test/java/com/ktb/joing/domain/user/service/UserServiceTest.java
Labels: feat

#15 JOING-30 feat: 기획서 생성 API 구현
  .DS_Store
  src/main/java/com/ktb/joing/domain/item/controller/ItemController.java
  src/main/java/com/ktb/joing/domain/item/dto/request/EtcRequest.java
  src/main/java/com/ktb/joing/domain/item/dto/request/ItemCreateRequest.java
  src/main/java/com/ktb/joing/domain/item/dto/response/EtcResponse.java
  src/main/java/com/ktb/joing/domain/item/dto/response/ItemCreateResponse.java
  src/main/java/com/ktb/joing/domain/item/entity/Etc.java
  src/main/java/com/ktb/joing/domain/item/entity/Item.java
  src/main/java/com/ktb/joing/domain/item/entity/Summary.java
  src/main/java/com/ktb/joing/domain/item/exception/ItemErrorCode.java
  src/main/java/com/ktb/joing/domain/item/exception/ItemException.java
  src/main/java/com/ktb/joing/domain/item/repository/ItemRepository.java
  src/main/java/com/ktb/joing/domain/item/service/ItemService.java
  src/main/java/com/ktb/joing/domain/user/entity/ProductManager.java
  src/main/resources/application-security.yml
  src/test/java/com/ktb/joing/domain/item/service/ItemServiceTest.java
Labels: feat

#13 JOING-37 chore: Dockerfile 수정
  Dockerfile
Labels: bug

#17 JOING-32 feat: 기획안 수정 API 구현
  src/main/java/com/ktb/joing/domain/item/controller/ItemController.java
  src/main/java/com/ktb/joing/domain/item/dto/request/EtcRequest.java
  src/main/java/com/ktb/joing/domain/item/dto/request/ItemUpdateRequest.java
  src/main/java/com/ktb/joing/domain/item/dto/response/ItemResponse.java
  src/main/java/com/ktb/joing/domain/item/entity/Etc.java
  src/main/java/com/ktb/joing/domain/item/entity/Item.java
  src/main/java/com/ktb/joing/domain/item/entity/Summary.java
  src/main/java/com/ktb/joing/domain/item/exception/ItemErrorCode.java
  src/main/java/com/ktb/joing/domain/item/service/ItemService.java
  src/test/java/com/ktb/joing/domain/item/service/ItemServiceTest.java
Labels: feat

#18 JOING-33 feat: 기획안 삭제 API 구현
  src/main/java/com/ktb/joing/domain/item/controller/ItemController.java
  src/main/java/com/ktb/joing/domain/item/entity/Item.java
  src/main/java/com/ktb/joing/domain/item/service/ItemService.java
Labels: feat

#19 JOING-31 feat: 기획안 조회 API 구현
  src/main/java/com/ktb/joing/domain/item/controller/ItemController.java
  src/main/java/com/ktb/joing/domain/item/dto/response/ItemRecentResponse.java
  src/main/java/com/ktb/joing/domain/item/repository/ItemRepository.java
  src/main/java/com/ktb/joing/domain/item/service/ItemService.java
Labels: feat

#16 JOING-38 test: 빌드 테스트 GitHub Action
  .github/workflows/test.yaml
  src/main/resources/application-database.yml
Labels: enhancement

#20 JOING-35 feat: 기획안 평가 및 요약 생성 API 구현
  build.gradle
  src/main/java/com/ktb/joing/common/config/WebClientConfig.java
  src/main/java/com/ktb/joing/common/exception/AiErrorCode.java
  src/main/java/com/ktb/joing/common/exception/AiException.java
  src/main/java/com/ktb/joing/common/util/webClient/ReactiveHttpService.java
  src/main/java/com/ktb/joing/domain/item/controller/ItemEvaluationController.java
  src/main/java/com/ktb/joing/domain/item/dto/request/ItemEvaluationRequest.java
  src/main/java/com/ktb/joing/domain/item/dto/response/EvaluationResponse.java
  src/main/java/com/ktb/joing/domain/item/dto/response/FeedbackResponse.java
  src/main/java/com/ktb/joing/domain/item/dto/response/FeedbackView.java
  src/main/java/com/ktb/joing/domain/item/dto/response/ItemEvaluationResponse.java
  src/main/java/com/ktb/joing/domain/item/dto/response/ResponseType.java
  src/main/java/com/ktb/joing/domain/item/dto/response/SummaryResponse.java
  src/main/java/com/ktb/joing/domain/item/dto/response/SummaryView.java
  src/main/java/com/ktb/joing/domain/item/entity/Item.java
  src/main/java/com/ktb/joing/domain/item/entity/Summary.java
  src/main/java/com/ktb/joing/domain/item/exception/ItemErrorCode.java
  src/main/java/com/ktb/joing/domain/item/service/ItemEvaluationService.java
  src/main/java/com/ktb/joing/domain/item/service/ItemSummaryService.java
Labels: feat

#24 JOING-43 feat: redis 임시저장소에서 MySql 임시저장소로 변경
  src/main/java/com/ktb/joing/common/config/SecurityConfig.java
  src/main/java/com/ktb/joing/domain/auth/entity/TempUser.java
  src/main/java/com/ktb/joing/domain/auth/handler/CustomSuccessHandler.java
  src/main/java/com/ktb/joing/domain/auth/jwt/JwtUtil.java
  src/main/java/com/ktb/joing/domain/auth/jwt/TokenService.java
  src/main/java/com/ktb/joing/domain/auth/redis/TempUser.java
  src/main/java/com/ktb/joing/domain/auth/redis/TempUserRepository.java
  src/main/java/com/ktb/joing/domain/auth/repository/TempUserRepository.java
  src/main/java/com/ktb/joing/domain/auth/service/CustomOAuth2UserService.java
  src/main/java/com/ktb/joing/domain/user/controller/UserController.java
  src/main/java/com/ktb/joing/domain/user/dto/request/CreatorSignupRequest.java
  src/main/java/com/ktb/joing/domain/user/entity/Creator.java
  src/main/java/com/ktb/joing/domain/user/entity/Role.java
  src/main/java/com/ktb/joing/domain/user/service/UserService.java
  src/test/java/com/ktb/joing/domain/user/service/UserServiceTest.java
Labels: feat

#27 JOING-43 feat: 로그아웃 API 구현
  src/main/java/com/ktb/joing/common/config/SecurityConfig.java
  src/main/java/com/ktb/joing/domain/auth/exception/AuthErrorCode.java
  src/main/java/com/ktb/joing/domain/auth/handler/CustomSuccessHandler.java
  src/main/java/com/ktb/joing/domain/auth/jwt/CustomLogoutFilter.java
  src/main/java/com/ktb/joing/domain/user/controller/UserController.java
Labels: feat

#29 JOING-49 feat: JWT 인증 관련 버그 수정
  src/main/java/com/ktb/joing/common/config/SecurityConfig.java
  src/main/java/com/ktb/joing/domain/auth/handler/CustomSuccessHandler.java
  src/main/java/com/ktb/joing/domain/auth/jwt/JwtFilter.java
  src/main/java/com/ktb/joing/domain/auth/jwt/TokenService.java
Labels: feat
